### ISSUE TITLE
libgvfsdbus.so

### ISSUE THREAD

**Issue by eskimgv** [meliksah/lcs#2]
Merhaba,
Belki de bilmediğim basit bir çözümü vardır.
Öncelikle windows bilgisayarımı offline kullanıyorum, uygulamanın kurulumunda bir sorun olmadı,
Ancak ubuntu bilgisayarımda ise uygulamayı komut satırından belirttiğiniz gibi çalıştırdığımda sağ üst tarafta uygulama icon'u geliyor. Sağ tıklayıp settings'e tıkladığımda uygulama bu şekilde kapanıyor.

Klavye bulunan PC değiştirme tuşlarından birine basınca farenin de aynı PC'yi otomatik seçeceğini umarak denemek istedim. Sizin düşündüğünüz senaryo da bu şekilde ise tam ihtiyacım olan şey. Müsait olduğunuzda inceleyebilirseniz memnun olurum. Elinize sağlık. Saygılarımla.

```
abdullah:~/Downloads$ chmod +x logitech_channel_switcher-linux
abdullah:~/Downloads$ sudo ./logitech_channel_switcher-linux
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
SystemTrayIcon init
SettingsDialog init
malloc(): invalid size (unsorted)
Aborted
```

**Comment by meliksah** [comment]
Bu uygulamada klayve tusuna basarak farenin kanalini degistirmek yerine ekranin belirli bir bolgesine gidince fare ve klavyenin kanalini degistirmek icin kullaniliyor cikan hatayi kendi sistemimde alamadigim icin de cok yardimci olamayacagim ->


It looks like you're encountering several issues while trying to run the logitech_channel_switcher-linux program on your Linux system. Let's break down the errors and suggest possible solutions:

QStandardPaths: XDG_RUNTIME_DIR not set: This warning indicates that the XDG_RUNTIME_DIR environment variable is not set. This variable typically points to a user-specific directory for non-essential runtime files and other file objects (such as sockets, named pipes, etc.). To fix this, you can set the XDG_RUNTIME_DIR before running your program. For example:
```
export XDG_RUNTIME_DIR=/run/user/$(id -u)
Replace $(id -u) with your actual user ID if necessary.
```
undefined symbol: g_task_set_static_name: This error suggests a problem with the libgvfscommon.so library, possibly due to version mismatch or corruption. GVFS (GNOME Virtual File System) is often used for file system abstraction in GNOME environments. To resolve this:

Try updating your system to ensure all libraries are up to date.

If you're using a Debian-based system (like Ubuntu), you can run:

```
sudo apt-get update
sudo apt-get upgrade
```
Alternatively, consider reinstalling the GVFS packages.

Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so: This is related to the above error and suggests an issue with the GVFS D-Bus module. Again, updating or reinstalling GVFS-related packages might help.

malloc(): invalid size (unsorted) & Aborted: This indicates a memory allocation issue, which could be due to a bug in the logitech_channel_switcher-linux program itself or a compatibility issue with your system's libraries. If updating your system doesn't resolve the issue, consider reaching out to the maintainers of the program for support.

Remember to always back up important data before making significant changes to your system, and consider running such updates and fixes in a test environment first if possible.
